//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySite.ServiceCalledFromWebSite {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/AccountWebService")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceCalledFromWebSite.IAccountWebService")]
    public interface IAccountWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountWebService/GetData", ReplyAction="http://tempuri.org/IAccountWebService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountWebService/GetData", ReplyAction="http://tempuri.org/IAccountWebService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountWebService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IAccountWebService/GetDataUsingDataContractResponse")]
        MySite.ServiceCalledFromWebSite.CompositeType GetDataUsingDataContract(MySite.ServiceCalledFromWebSite.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountWebService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IAccountWebService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<MySite.ServiceCalledFromWebSite.CompositeType> GetDataUsingDataContractAsync(MySite.ServiceCalledFromWebSite.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountWebService/CreateAccount", ReplyAction="http://tempuri.org/IAccountWebService/CreateAccountResponse")]
        void CreateAccount(int entityNumber, string name, string website);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountWebService/CreateAccount", ReplyAction="http://tempuri.org/IAccountWebService/CreateAccountResponse")]
        System.Threading.Tasks.Task CreateAccountAsync(int entityNumber, string name, string website);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAccountWebServiceChannel : MySite.ServiceCalledFromWebSite.IAccountWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountWebServiceClient : System.ServiceModel.ClientBase<MySite.ServiceCalledFromWebSite.IAccountWebService>, MySite.ServiceCalledFromWebSite.IAccountWebService {
        
        public AccountWebServiceClient() {
        }
        
        public AccountWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public MySite.ServiceCalledFromWebSite.CompositeType GetDataUsingDataContract(MySite.ServiceCalledFromWebSite.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<MySite.ServiceCalledFromWebSite.CompositeType> GetDataUsingDataContractAsync(MySite.ServiceCalledFromWebSite.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public void CreateAccount(int entityNumber, string name, string website) {
            base.Channel.CreateAccount(entityNumber, name, website);
        }
        
        public System.Threading.Tasks.Task CreateAccountAsync(int entityNumber, string name, string website) {
            return base.Channel.CreateAccountAsync(entityNumber, name, website);
        }
    }
}
